FINAL:0x0 EXT:
FUNC:0 N0
add_i64 [t0],rip,0xa
add_i64 [t1],rsp,0xfffffffffffffff8
mov_i64 [t2],t1
qemu_st_i64 t0,t2,attr-stg:ATOM_NONE:UNALIGNED:ZERO:SRC8B,0x2
mov_i64 [rsp],t1
ld_i64 [t3],env:0xfffffffffffffff8
add_i64 [t3],t3,0xfffffffffffffff8
qemu_st_i64 t0,t3,attr-stg:ATOM_IFALIGN:ALIGN_8:ZERO:SRC8B
add_i64 [t3],t3,0xfffffffffffffff8
func_addr t4,0x88a,0x0
qemu_st_i64 t4,t3,attr-stg:ATOM_IFALIGN:ALIGN_8:ZERO:SRC8B
st_i64 t3,env:0xfffffffffffffff8

