FINAL:0x0 EXT:
FUNC:0 N0
mov_i64 [t0],0x42
mov_i64 [t1],0x42
ld_i64 [t8],env:0xfffffffffffffff8
sub_i64 [t9],t8,0x10
qemu_st_i64 t0,t9,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t9],t8,0x20
qemu_st_i64 t1,t9,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
func_addr t20,helper_punpckhbw_xmm,v10,v10,v0
func_addr t21,0x0,0x1
tail_call_qemuaot t20,t21 VEC_ARGS:v10,v10,v0,

FUNC:0 N1
ld_i64 [t10],env:0xfffffffffffffff8
sub_i64 [t11],t10,0x10
qemu_ld_i64 [t0],t11,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t11],t10,0x20
qemu_ld_i64 [t1],t11,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
mov_i64 [t5],t0
mov_i64 [t6],t1
mov_i64 [t0],0x0
func_addr t22,helper_movmskps_xmm
func_addr t23,0x0,0x2
tail_call_qemuaot t22,t7,t23 VEC_ARGS:

FUNC:0 N2
mov_i64 [t0],__last_arg__
set_label L0
mov_i64 [t5],t0
mov_i64 [t0],0x0
ld_i64 [t12],env:0xfffffffffffffff8
sub_i64 [t13],t12,0x10
qemu_st_i64 t0,t13,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t13],t12,0x20
qemu_st_i64 t1,t13,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t13],t12,0x30
qemu_st_i64 t5,t13,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t13],t12,0x40
qemu_st_i64 t6,t13,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
func_addr t24,helper_movmskps_xmm
func_addr t25,0x0,0x3
tail_call_qemuaot t24,t7,t25 VEC_ARGS:

FUNC:0 N3
mov_i64 [t3],__last_arg__
ld_i64 [t14],env:0xfffffffffffffff8
sub_i64 [t15],t14,0x10
qemu_ld_i64 [t0],t15,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t15],t14,0x20
qemu_ld_i64 [t1],t15,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t15],t14,0x30
qemu_ld_i64 [t5],t15,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t15],t14,0x40
qemu_ld_i64 [t6],t15,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
mov_i64 [t5],t0
ld_i64 [t16],env:0xfffffffffffffff8
sub_i64 [t17],t16,0x10
qemu_st_i64 t0,t17,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t17],t16,0x20
qemu_st_i64 t1,t17,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t17],t16,0x30
qemu_st_i64 t5,t17,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t17],t16,0x40
qemu_st_i64 t6,t17,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
func_addr t26,helper_movmskps_xmm
func_addr t27,0x0,0x4
tail_call_qemuaot t26,t7,t27 VEC_ARGS:

FUNC:0 N4
mov_i64 [t3],__last_arg__
ld_i64 [t18],env:0xfffffffffffffff8
sub_i64 [t19],t18,0x10
qemu_ld_i64 [t0],t19,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t19],t18,0x20
qemu_ld_i64 [t1],t19,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t19],t18,0x30
qemu_ld_i64 [t5],t19,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
sub_i64 [t19],t18,0x40
qemu_ld_i64 [t6],t19,attr-stg:ATOM_IFALIGN:ALIGN_16:ZERO:SRC8B
br L0

