FINAL:0x0 EXT:
FUNC:0 N0
func_addr t6,helper_punpcklqdq_ymm,v10,v11,v10,v11,v2,v3
func_addr t7,0x0,0x1
st_vec v128,e8,v2,env:0x3a0
ld_vec v128,e8,[v2],env:0xb60
st_vec v128,e8,v3,env:0x3b0
ld_vec v128,e8,[v3],env:0xb70
tail_call_qemuaot t6,t7 VEC_ARGS:v10,v11,v10,v11,v2,v3,

FUNC:0 N1
st_vec v128,e8,v2,env:0xb60
ld_vec v128,e8,[v2],env:0x3a0
st_vec v128,e8,v3,env:0xb70
ld_vec v128,e8,[v3],env:0x3b0
mov_i64 [t3],0x42
ld_vec v128,e8,[t5],v2

