/*
 * Minimal Perfect Hash for QEMU helper function names (aarch64)
 *
 * GUARANTEED PROPERTIES:
 *   - Input: 1070 known helper function names
 *   - Output: slot in [0, 1070-1]
 *   - Collisions: ZERO (all names map to distinct slots)
 *   - Table overhead: 0 slots (100% utilization)
 *
 * Algorithm: CHD (Compress-Hash-Displace)
 *   Step 1: Primary hash → bucket (djb2 with golden ratio)
 *   Step 2: Secondary hash → slot (polynomial with per-bucket seed)
 *
 * Memory: 4280 bytes for seed array + 8560 bytes for dispatch table
 *       = 12.5 KB total
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>

#define HELPER_HASH_N 1070
#define HELPER_HASH_NB 1070

/* Bucket seeds for secondary hash.
 * Computed by CHD algorithm to guarantee no collisions.
 * 481 unique non-zero seeds + 589 zero seeds (for single-element buckets).
 */
static const uint32_t helper_hash_seeds[HELPER_HASH_NB] = {
    0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
    8, 1, 2, 0, 2, 2, 5, 0, 0, 0,
    1, 0, 0, 1, 7, 0, 0, 0, 1, 0,
    3, 1, 0, 1, 0, 2, 0, 2, 0, 0,
    0, 3, 0, 1, 0, 1, 0, 17, 2, 0,
    8, 0, 1, 0, 1, 0, 0, 0, 0, 0,
    0, 2, 0, 2, 0, 0, 4, 3, 4, 0,
    0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0, 0, 0, 8,
    0, 0, 0, 1, 0, 1, 0, 0, 3, 0,
    0, 0, 0, 18, 0, 0, 0, 0, 0, 6,
    0, 0, 1, 0, 0, 0, 0, 3, 0, 4,
    3, 2, 0, 0, 0, 0, 0, 1, 0, 0,
    0, 0, 3, 3, 1, 0, 0, 0, 0, 0,
    1, 0, 0, 2, 0, 5, 2, 0, 0, 3,
    0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
    0, 2, 0, 1, 0, 0, 0, 0, 0, 0,
    0, 3, 5, 0, 0, 0, 1, 1, 0, 1,
    0, 1, 0, 2, 0, 0, 0, 1, 0, 0,
    0, 4, 3, 0, 0, 0, 0, 7, 4, 2,
    0, 0, 0, 0, 0, 0, 0, 0, 3, 2,
    1, 0, 0, 2, 8, 1, 0, 5, 1, 0,
    8, 0, 2, 0, 0, 0, 1, 1, 1, 8,
    0, 1, 4, 0, 3, 0, 1, 1, 0, 0,
    0, 1, 0, 3, 9, 0, 4, 0, 7, 0,
    0, 0, 0, 1, 0, 0, 0, 0, 5, 0,
    0, 1, 13, 0, 1, 1, 1, 1, 0, 4,
    2, 2, 1, 2, 10, 0, 0, 4, 0, 0,
    0, 1, 0, 0, 0, 12, 0, 2, 2, 0,
    0, 1, 1, 0, 0, 10, 0, 0, 0, 6,
    1, 0, 0, 0, 2, 15, 0, 0, 0, 0,
    0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
    5, 4, 0, 0, 2, 0, 0, 4, 0, 2,
    10, 2, 0, 1, 0, 1, 0, 0, 0, 0,
    2, 0, 1, 0, 27, 0, 0, 0, 0, 0,
    3, 0, 0, 5, 0, 0, 3, 0, 0, 0,
    1, 0, 0, 0, 8, 0, 3, 0, 5, 1,
    1, 0, 0, 0, 0, 0, 4, 3, 0, 3,
    0, 0, 0, 2, 1, 1, 13, 3, 0, 0,
    1, 3, 0, 0, 1, 7, 0, 0, 15, 0,
    0, 1, 0, 0, 0, 0, 20, 0, 0, 0,
    0, 0, 0, 1, 2, 4, 0, 3, 2, 0,
    3, 0, 0, 0, 20, 0, 0, 8, 0, 0,
    4, 1, 0, 0, 0, 0, 2, 0, 2, 0,
    0, 16, 1, 0, 0, 2, 1, 5, 0, 16,
    0, 0, 0, 0, 0, 7, 11, 0, 0, 1,
    13, 0, 1, 0, 2, 0, 0, 5, 1, 0,
    0, 0, 1, 1, 4, 0, 0, 12, 2, 10,
    6, 1, 11, 0, 3, 5, 1, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 0, 6, 0, 0,
    0, 0, 0, 0, 0, 0, 7, 4, 0, 0,
    1, 8, 1, 4, 12, 0, 0, 1, 2, 0,
    3, 0, 11, 8, 0, 0, 1, 2, 2, 5,
    0, 0, 0, 6, 0, 3, 9, 0, 2, 2,
    0, 0, 0, 3, 0, 0, 4, 0, 13, 6,
    0, 5, 0, 7, 0, 26, 4, 0, 0, 11,
    0, 0, 0, 0, 0, 0, 12, 0, 0, 1,
    0, 0, 1, 4, 0, 0, 0, 0, 20, 3,
    0, 14, 0, 0, 5, 0, 3, 22, 0, 2,
    0, 1, 0, 5, 0, 3, 13, 0, 5, 0,
    0, 2, 0, 0, 0, 0, 3, 0, 0, 0,
    5, 3, 0, 12, 0, 0, 4, 0, 5, 0,
    0, 0, 2, 1, 1, 11, 0, 0, 0, 1,
    2, 0, 2, 0, 0, 0, 0, 0, 1, 4,
    1, 4, 28, 0, 2, 1, 0, 10, 2, 7,
    2, 0, 4, 2, 0, 1, 6, 2, 2, 1,
    0, 4, 5, 3, 2, 1, 15, 3, 0, 1,
    0, 5, 5, 0, 8, 0, 2, 0, 0, 10,
    0, 1, 0, 0, 0, 7, 0, 3, 3, 0,
    0, 17, 0, 2, 0, 0, 0, 0, 9, 0,
    0, 0, 1, 0, 5, 8, 0, 2, 0, 5,
    0, 6, 0, 8, 0, 0, 10, 0, 4, 0,
    5, 0, 0, 8, 6, 0, 3, 1, 0, 0,
    1, 4, 0, 0, 0, 7, 0, 15, 0, 0,
    6, 5, 7, 20, 10, 0, 0, 0, 0, 0,
    0, 8, 0, 1, 4, 0, 0, 2, 5, 0,
    0, 7, 3, 6, 0, 0, 0, 1, 0, 0,
    3, 9, 0, 6, 0, 0, 12, 1, 3, 9,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 3, 0, 0, 0, 0, 0, 2, 0, 6,
    0, 0, 0, 16, 0, 0, 5, 0, 18, 8,
    0, 2, 4, 0, 10, 16, 0, 0, 3, 0,
    0, 3, 0, 0, 0, 1, 0, 13, 20, 0,
    0, 26, 58, 22, 0, 27, 9, 2, 1, 0,
    0, 0, 12, 0, 0, 0, 0, 0, 7, 0,
    5, 0, 3, 4, 0, 5, 0, 3, 0, 0,
    3, 0, 0, 3, 0, 4, 0, 7, 10, 29,
    4, 0, 0, 23, 0, 0, 1, 0, 9, 0,
    7, 0, 0, 9, 14, 19, 1, 0, 12, 0,
    24, 25, 3, 0, 0, 14, 3, 0, 0, 0,
    22, 0, 4, 0, 2, 5, 0, 0, 0, 0,
    19, 24, 0, 0, 12, 0, 13, 0, 0, 0,
    0, 0, 1, 1, 0, 20, 58, 0, 7, 0,
    47, 73, 0, 0, 3, 0, 7, 21, 0, 0,
    9, 0, 2, 0, 29, 0, 0, 42, 14, 0,
    1, 10, 0, 0, 20, 0, 0, 14, 2, 8,
    4, 8, 23, 0, 44, 0, 0, 0, 0, 16,
    0, 10, 0, 14, 3, 0, 0, 10, 42, 5,
    554, 0, 0, 2, 50, 0, 1, 0, 19, 0,
    41, 91, 0, 0, 0, 0, 0, 21, 2, 13,
    62, 42, 0, 60, 31, 19, 6, 13, 0, 4,
    11, 2, 0, 0, 0, 2, 4, 147, 0, 0,
    32, 0, 3, 3, 3, 10, 41, 24, 86, 0,
    0, 81, 154, 0, 0, 0, 3, 3, 21050, 10,
    1, 0, 113, 1, 19, 0, 0, 63, 54, 1,
    19, 0, 0, 173, 0, 68, 159, 0, 0, 945,
    57, 0, 28, 70, 0, 0, 94, 0, 604, 805,
};

/* Primary hash: djb2 variant.
 *   h = golden_ratio * HELPER_HASH_NB  (initial value)
 *   for each char: h = h*33 + char     (with uint32_t wrap)
 */
static inline uint32_t helper_primary_hash(const char *name)
{
    uint32_t h = (uint32_t)((uint64_t)HELPER_HASH_NB * 2654435761ULL);
    for (const char *p = name; *p; p++) {
        h = ((h << 5) + h + (uint8_t)*p);
    }
    return h;
}

/* Secondary hash: polynomial with per-bucket seed.
 *   h = seed  (initial value from bucket)
 *   for each char: h = h*31 + char  (with uint32_t wrap)
 */
static inline uint32_t helper_secondary_hash(const char *name, uint32_t seed)
{
    uint32_t h = seed;
    for (const char *p = name; *p; p++) {
        h = h * 31 + (uint8_t)*p;
    }
    return h;
}

/* Minimal perfect hash function.
 * Returns slot index in [0, HELPER_HASH_N-1] for valid helper names.
 * Returns -1 if the name is not in the known set.
 */
static inline int32_t helper_name_hash(const char *name)
{
    uint32_t h = helper_primary_hash(name);
    uint32_t bucket = h % HELPER_HASH_NB;
    uint32_t seed = helper_hash_seeds[bucket];
    uint32_t h2 = helper_secondary_hash(name, seed);
    return (int32_t)(h2 % HELPER_HASH_N);
}

/* Also provide a comparison-based fallback for safety.
 * This allows the caller to verify the hash result.
 */

static const char *helper_names[HELPER_HASH_N] = {
    "helper_div_i32",
    "helper_rem_i32",
    "helper_divu_i32",
    "helper_remu_i32",
    "helper_div_i64",
    "helper_rem_i64",
    "helper_divu_i64",
    "helper_remu_i64",
    "helper_shl_i64",
    "helper_shr_i64",
    "helper_sar_i64",
    "helper_mulsh_i64",
    "helper_muluh_i64",
    "helper_clz_i32",
    "helper_ctz_i32",
    "helper_clz_i64",
    "helper_ctz_i64",
    "helper_clrsb_i32",
    "helper_clrsb_i64",
    "helper_ctpop_i32",
    "helper_ctpop_i64",
    "helper_lookup_tb_ptr",
    "helper_exit_atomic",
    "memset",
    "helper_ld_i128",
    "helper_st_i128",
    "helper_atomic_cmpxchgb",
    "helper_atomic_cmpxchgw_be",
    "helper_atomic_cmpxchgw_le",
    "helper_atomic_cmpxchgl_be",
    "helper_atomic_cmpxchgl_le",
    "helper_atomic_cmpxchgq_be",
    "helper_atomic_cmpxchgq_le",
    "helper_atomic_cmpxchgo_be",
    "helper_atomic_cmpxchgo_le",
    "helper_nonatomic_cmpxchgo",
    "helper_atomic_fetch_addb",
    "helper_atomic_fetch_addw_le",
    "helper_atomic_fetch_addw_be",
    "helper_atomic_fetch_addl_le",
    "helper_atomic_fetch_addl_be",
    "helper_atomic_fetch_addq_le",
    "helper_atomic_fetch_addq_be",
    "helper_atomic_fetch_andb",
    "helper_atomic_fetch_andw_le",
    "helper_atomic_fetch_andw_be",
    "helper_atomic_fetch_andl_le",
    "helper_atomic_fetch_andl_be",
    "helper_atomic_fetch_andq_le",
    "helper_atomic_fetch_andq_be",
    "helper_atomic_fetch_orb",
    "helper_atomic_fetch_orw_le",
    "helper_atomic_fetch_orw_be",
    "helper_atomic_fetch_orl_le",
    "helper_atomic_fetch_orl_be",
    "helper_atomic_fetch_orq_le",
    "helper_atomic_fetch_orq_be",
    "helper_atomic_fetch_xorb",
    "helper_atomic_fetch_xorw_le",
    "helper_atomic_fetch_xorw_be",
    "helper_atomic_fetch_xorl_le",
    "helper_atomic_fetch_xorl_be",
    "helper_atomic_fetch_xorq_le",
    "helper_atomic_fetch_xorq_be",
    "helper_atomic_fetch_sminb",
    "helper_atomic_fetch_sminw_le",
    "helper_atomic_fetch_sminw_be",
    "helper_atomic_fetch_sminl_le",
    "helper_atomic_fetch_sminl_be",
    "helper_atomic_fetch_sminq_le",
    "helper_atomic_fetch_sminq_be",
    "helper_atomic_fetch_uminb",
    "helper_atomic_fetch_uminw_le",
    "helper_atomic_fetch_uminw_be",
    "helper_atomic_fetch_uminl_le",
    "helper_atomic_fetch_uminl_be",
    "helper_atomic_fetch_uminq_le",
    "helper_atomic_fetch_uminq_be",
    "helper_atomic_fetch_smaxb",
    "helper_atomic_fetch_smaxw_le",
    "helper_atomic_fetch_smaxw_be",
    "helper_atomic_fetch_smaxl_le",
    "helper_atomic_fetch_smaxl_be",
    "helper_atomic_fetch_smaxq_le",
    "helper_atomic_fetch_smaxq_be",
    "helper_atomic_fetch_umaxb",
    "helper_atomic_fetch_umaxw_le",
    "helper_atomic_fetch_umaxw_be",
    "helper_atomic_fetch_umaxl_le",
    "helper_atomic_fetch_umaxl_be",
    "helper_atomic_fetch_umaxq_le",
    "helper_atomic_fetch_umaxq_be",
    "helper_atomic_add_fetchb",
    "helper_atomic_add_fetchw_le",
    "helper_atomic_add_fetchw_be",
    "helper_atomic_add_fetchl_le",
    "helper_atomic_add_fetchl_be",
    "helper_atomic_add_fetchq_le",
    "helper_atomic_add_fetchq_be",
    "helper_atomic_and_fetchb",
    "helper_atomic_and_fetchw_le",
    "helper_atomic_and_fetchw_be",
    "helper_atomic_and_fetchl_le",
    "helper_atomic_and_fetchl_be",
    "helper_atomic_and_fetchq_le",
    "helper_atomic_and_fetchq_be",
    "helper_atomic_or_fetchb",
    "helper_atomic_or_fetchw_le",
    "helper_atomic_or_fetchw_be",
    "helper_atomic_or_fetchl_le",
    "helper_atomic_or_fetchl_be",
    "helper_atomic_or_fetchq_le",
    "helper_atomic_or_fetchq_be",
    "helper_atomic_xor_fetchb",
    "helper_atomic_xor_fetchw_le",
    "helper_atomic_xor_fetchw_be",
    "helper_atomic_xor_fetchl_le",
    "helper_atomic_xor_fetchl_be",
    "helper_atomic_xor_fetchq_le",
    "helper_atomic_xor_fetchq_be",
    "helper_atomic_smin_fetchb",
    "helper_atomic_smin_fetchw_le",
    "helper_atomic_smin_fetchw_be",
    "helper_atomic_smin_fetchl_le",
    "helper_atomic_smin_fetchl_be",
    "helper_atomic_smin_fetchq_le",
    "helper_atomic_smin_fetchq_be",
    "helper_atomic_umin_fetchb",
    "helper_atomic_umin_fetchw_le",
    "helper_atomic_umin_fetchw_be",
    "helper_atomic_umin_fetchl_le",
    "helper_atomic_umin_fetchl_be",
    "helper_atomic_umin_fetchq_le",
    "helper_atomic_umin_fetchq_be",
    "helper_atomic_smax_fetchb",
    "helper_atomic_smax_fetchw_le",
    "helper_atomic_smax_fetchw_be",
    "helper_atomic_smax_fetchl_le",
    "helper_atomic_smax_fetchl_be",
    "helper_atomic_smax_fetchq_le",
    "helper_atomic_smax_fetchq_be",
    "helper_atomic_umax_fetchb",
    "helper_atomic_umax_fetchw_le",
    "helper_atomic_umax_fetchw_be",
    "helper_atomic_umax_fetchl_le",
    "helper_atomic_umax_fetchl_be",
    "helper_atomic_umax_fetchq_le",
    "helper_atomic_umax_fetchq_be",
    "helper_atomic_xchgb",
    "helper_atomic_xchgw_le",
    "helper_atomic_xchgw_be",
    "helper_atomic_xchgl_le",
    "helper_atomic_xchgl_be",
    "helper_atomic_xchgq_le",
    "helper_atomic_xchgq_be",
    "helper_gvec_mov",
    "helper_gvec_dup8",
    "helper_gvec_dup16",
    "helper_gvec_dup32",
    "helper_gvec_dup64",
    "helper_gvec_add8",
    "helper_gvec_add16",
    "helper_gvec_add32",
    "helper_gvec_add64",
    "helper_gvec_adds8",
    "helper_gvec_adds16",
    "helper_gvec_adds32",
    "helper_gvec_adds64",
    "helper_gvec_sub8",
    "helper_gvec_sub16",
    "helper_gvec_sub32",
    "helper_gvec_sub64",
    "helper_gvec_subs8",
    "helper_gvec_subs16",
    "helper_gvec_subs32",
    "helper_gvec_subs64",
    "helper_gvec_mul8",
    "helper_gvec_mul16",
    "helper_gvec_mul32",
    "helper_gvec_mul64",
    "helper_gvec_muls8",
    "helper_gvec_muls16",
    "helper_gvec_muls32",
    "helper_gvec_muls64",
    "helper_gvec_ssadd8",
    "helper_gvec_ssadd16",
    "helper_gvec_ssadd32",
    "helper_gvec_ssadd64",
    "helper_gvec_sssub8",
    "helper_gvec_sssub16",
    "helper_gvec_sssub32",
    "helper_gvec_sssub64",
    "helper_gvec_usadd8",
    "helper_gvec_usadd16",
    "helper_gvec_usadd32",
    "helper_gvec_usadd64",
    "helper_gvec_ussub8",
    "helper_gvec_ussub16",
    "helper_gvec_ussub32",
    "helper_gvec_ussub64",
    "helper_gvec_smin8",
    "helper_gvec_smin16",
    "helper_gvec_smin32",
    "helper_gvec_smin64",
    "helper_gvec_smax8",
    "helper_gvec_smax16",
    "helper_gvec_smax32",
    "helper_gvec_smax64",
    "helper_gvec_umin8",
    "helper_gvec_umin16",
    "helper_gvec_umin32",
    "helper_gvec_umin64",
    "helper_gvec_umax8",
    "helper_gvec_umax16",
    "helper_gvec_umax32",
    "helper_gvec_umax64",
    "helper_gvec_neg8",
    "helper_gvec_neg16",
    "helper_gvec_neg32",
    "helper_gvec_neg64",
    "helper_gvec_abs8",
    "helper_gvec_abs16",
    "helper_gvec_abs32",
    "helper_gvec_abs64",
    "helper_gvec_not",
    "helper_gvec_and",
    "helper_gvec_or",
    "helper_gvec_xor",
    "helper_gvec_andc",
    "helper_gvec_orc",
    "helper_gvec_nand",
    "helper_gvec_nor",
    "helper_gvec_eqv",
    "helper_gvec_ands",
    "helper_gvec_andcs",
    "helper_gvec_xors",
    "helper_gvec_ors",
    "helper_gvec_shl8i",
    "helper_gvec_shl16i",
    "helper_gvec_shl32i",
    "helper_gvec_shl64i",
    "helper_gvec_shr8i",
    "helper_gvec_shr16i",
    "helper_gvec_shr32i",
    "helper_gvec_shr64i",
    "helper_gvec_sar8i",
    "helper_gvec_sar16i",
    "helper_gvec_sar32i",
    "helper_gvec_sar64i",
    "helper_gvec_rotl8i",
    "helper_gvec_rotl16i",
    "helper_gvec_rotl32i",
    "helper_gvec_rotl64i",
    "helper_gvec_shl8v",
    "helper_gvec_shl16v",
    "helper_gvec_shl32v",
    "helper_gvec_shl64v",
    "helper_gvec_shr8v",
    "helper_gvec_shr16v",
    "helper_gvec_shr32v",
    "helper_gvec_shr64v",
    "helper_gvec_sar8v",
    "helper_gvec_sar16v",
    "helper_gvec_sar32v",
    "helper_gvec_sar64v",
    "helper_gvec_rotl8v",
    "helper_gvec_rotl16v",
    "helper_gvec_rotl32v",
    "helper_gvec_rotl64v",
    "helper_gvec_rotr8v",
    "helper_gvec_rotr16v",
    "helper_gvec_rotr32v",
    "helper_gvec_rotr64v",
    "helper_gvec_eq8",
    "helper_gvec_eq16",
    "helper_gvec_eq32",
    "helper_gvec_eq64",
    "helper_gvec_ne8",
    "helper_gvec_ne16",
    "helper_gvec_ne32",
    "helper_gvec_ne64",
    "helper_gvec_lt8",
    "helper_gvec_lt16",
    "helper_gvec_lt32",
    "helper_gvec_lt64",
    "helper_gvec_le8",
    "helper_gvec_le16",
    "helper_gvec_le32",
    "helper_gvec_le64",
    "helper_gvec_ltu8",
    "helper_gvec_ltu16",
    "helper_gvec_ltu32",
    "helper_gvec_ltu64",
    "helper_gvec_leu8",
    "helper_gvec_leu16",
    "helper_gvec_leu32",
    "helper_gvec_leu64",
    "helper_gvec_eqs8",
    "helper_gvec_eqs16",
    "helper_gvec_eqs32",
    "helper_gvec_eqs64",
    "helper_gvec_lts8",
    "helper_gvec_lts16",
    "helper_gvec_lts32",
    "helper_gvec_lts64",
    "helper_gvec_les8",
    "helper_gvec_les16",
    "helper_gvec_les32",
    "helper_gvec_les64",
    "helper_gvec_ltus8",
    "helper_gvec_ltus16",
    "helper_gvec_ltus32",
    "helper_gvec_ltus64",
    "helper_gvec_leus8",
    "helper_gvec_leus16",
    "helper_gvec_leus32",
    "helper_gvec_leus64",
    "helper_gvec_bitsel",
    "helper_jmp_ind",
    "AES_sbox",
    "helper_jit",
    "helper_iret_ind",
    "helper_cc_compute_all",
    "helper_cc_compute_c",
    "helper_cc_compute_nz",
    "helper_write_eflags",
    "helper_read_eflags",
    "helper_divb_AL",
    "helper_idivb_AL",
    "helper_divw_AX",
    "helper_idivw_AX",
    "helper_divl_EAX",
    "helper_idivl_EAX",
    "helper_divq_EAX",
    "helper_idivq_EAX",
    "helper_cr4_testbit",
    "helper_bndck",
    "helper_bndldx32",
    "helper_bndldx64",
    "helper_bndstx32",
    "helper_bndstx64",
    "helper_bnd_jmp",
    "helper_aam",
    "helper_aad",
    "helper_aaa",
    "helper_aas",
    "helper_daa",
    "helper_das",
    "helper_lsl",
    "helper_lar",
    "helper_verr",
    "helper_verw",
    "helper_lldt",
    "helper_ltr",
    "helper_load_seg",
    "helper_ljmp_protected",
    "helper_lcall_real",
    "helper_lcall_protected",
    "helper_iret_real",
    "helper_iret_protected",
    "helper_lret_protected",
    "helper_clts",
    "helper_sysenter",
    "helper_sysexit",
    "helper_syscall",
    "helper_sysret",
    "helper_pause",
    "helper_raise_interrupt",
    "helper_raise_exception",
    "helper_icebp",
    "helper_boundw",
    "helper_boundl",
    "helper_into",
    "helper_single_step",
    "helper_rechecking_single_step",
    "helper_cpuid",
    "helper_rdpid",
    "helper_rdtsc",
    "helper_rdpmc",
    "helper_flds_FT0",
    "helper_fldl_FT0",
    "helper_fildl_FT0",
    "helper_flds_ST0",
    "helper_fldl_ST0",
    "helper_fildl_ST0",
    "helper_fildll_ST0",
    "helper_fsts_ST0",
    "helper_fstl_ST0",
    "helper_fist_ST0",
    "helper_fistl_ST0",
    "helper_fistll_ST0",
    "helper_fistt_ST0",
    "helper_fisttl_ST0",
    "helper_fisttll_ST0",
    "helper_fldt_ST0",
    "helper_fstt_ST0",
    "helper_fpush",
    "helper_fpop",
    "helper_fdecstp",
    "helper_fincstp",
    "helper_ffree_STN",
    "helper_fmov_ST0_FT0",
    "helper_fmov_FT0_STN",
    "helper_fmov_ST0_STN",
    "helper_fmov_STN_ST0",
    "helper_fxchg_ST0_STN",
    "helper_fcom_ST0_FT0",
    "helper_fucom_ST0_FT0",
    "helper_fcomi_ST0_FT0",
    "helper_fucomi_ST0_FT0",
    "helper_fadd_ST0_FT0",
    "helper_fmul_ST0_FT0",
    "helper_fsub_ST0_FT0",
    "helper_fsubr_ST0_FT0",
    "helper_fdiv_ST0_FT0",
    "helper_fdivr_ST0_FT0",
    "helper_fadd_STN_ST0",
    "helper_fmul_STN_ST0",
    "helper_fsub_STN_ST0",
    "helper_fsubr_STN_ST0",
    "helper_fdiv_STN_ST0",
    "helper_fdivr_STN_ST0",
    "helper_fchs_ST0",
    "helper_fabs_ST0",
    "helper_fxam_ST0",
    "helper_fld1_ST0",
    "helper_fldl2t_ST0",
    "helper_fldl2e_ST0",
    "helper_fldpi_ST0",
    "helper_fldlg2_ST0",
    "helper_fldln2_ST0",
    "helper_fldz_ST0",
    "helper_fldz_FT0",
    "helper_fnstsw",
    "helper_fnstcw",
    "helper_fldcw",
    "helper_fclex",
    "helper_fwait",
    "helper_fninit",
    "helper_fbld_ST0",
    "helper_fbst_ST0",
    "helper_f2xm1",
    "helper_fyl2x",
    "helper_fptan",
    "helper_fpatan",
    "helper_fxtract",
    "helper_fprem1",
    "helper_fprem",
    "helper_fyl2xp1",
    "helper_fsqrt",
    "helper_fsincos",
    "helper_frndint",
    "helper_fscale",
    "helper_fsin",
    "helper_fcos",
    "helper_fstenv",
    "helper_fldenv",
    "helper_fsave",
    "helper_frstor",
    "helper_fxsave",
    "helper_fxrstor",
    "helper_xsave",
    "helper_xsaveopt",
    "helper_xrstor",
    "helper_xgetbv",
    "helper_xsetbv",
    "helper_rdpkru",
    "helper_wrpkru",
    "helper_pdep",
    "helper_pext",
    "helper_ldmxcsr",
    "helper_update_mxcsr",
    "helper_enter_mmx",
    "helper_emms",
    "helper_psrlw_mmx",
    "helper_psraw_mmx",
    "helper_psllw_mmx",
    "helper_psrld_mmx",
    "helper_psrad_mmx",
    "helper_pslld_mmx",
    "helper_psrlq_mmx",
    "helper_psllq_mmx",
    "helper_pmulhrw_mmx",
    "helper_pmulhuw_mmx",
    "helper_pmulhw_mmx",
    "helper_pavgb_mmx",
    "helper_pavgw_mmx",
    "helper_pmuludq_mmx",
    "helper_pmaddwd_mmx",
    "helper_psadbw_mmx",
    "helper_maskmov_mmx",
    "helper_pshufw_mmx",
    "helper_packsswb_mmx",
    "helper_packuswb_mmx",
    "helper_packssdw_mmx",
    "helper_punpcklbw_mmx",
    "helper_punpcklwd_mmx",
    "helper_punpckldq_mmx",
    "helper_punpckhbw_mmx",
    "helper_punpckhwd_mmx",
    "helper_punpckhdq_mmx",
    "helper_pi2fd",
    "helper_pi2fw",
    "helper_pf2id",
    "helper_pf2iw",
    "helper_pfacc",
    "helper_pfadd",
    "helper_pfcmpeq",
    "helper_pfcmpge",
    "helper_pfcmpgt",
    "helper_pfmax",
    "helper_pfmin",
    "helper_pfmul",
    "helper_pfnacc",
    "helper_pfpnacc",
    "helper_pfrcp",
    "helper_pfrsqrt",
    "helper_pfsub",
    "helper_pfsubr",
    "helper_pswapd",
    "helper_phaddw_mmx",
    "helper_phaddd_mmx",
    "helper_phaddsw_mmx",
    "helper_phsubw_mmx",
    "helper_phsubd_mmx",
    "helper_phsubsw_mmx",
    "helper_pmaddubsw_mmx",
    "helper_pmulhrsw_mmx",
    "helper_pshufb_mmx",
    "helper_psignb_mmx",
    "helper_psignw_mmx",
    "helper_psignd_mmx",
    "helper_palignr_mmx",
    "helper_psrlw_xmm",
    "helper_psraw_xmm",
    "helper_psllw_xmm",
    "helper_psrld_xmm",
    "helper_psrad_xmm",
    "helper_pslld_xmm",
    "helper_psrlq_xmm",
    "helper_psllq_xmm",
    "helper_psrldq_xmm",
    "helper_pslldq_xmm",
    "helper_pmulhuw_xmm",
    "helper_pmulhw_xmm",
    "helper_pavgb_xmm",
    "helper_pavgw_xmm",
    "helper_pmuludq_xmm",
    "helper_pmaddwd_xmm",
    "helper_psadbw_xmm",
    "helper_maskmov_xmm",
    "helper_pshufd_xmm",
    "helper_pshuflw_xmm",
    "helper_pshufhw_xmm",
    "helper_shufps_xmm",
    "helper_shufpd_xmm",
    "helper_addps_xmm",
    "helper_addpd_xmm",
    "helper_addss",
    "helper_addsd",
    "helper_subps_xmm",
    "helper_subpd_xmm",
    "helper_subss",
    "helper_subsd",
    "helper_mulps_xmm",
    "helper_mulpd_xmm",
    "helper_mulss",
    "helper_mulsd",
    "helper_divps_xmm",
    "helper_divpd_xmm",
    "helper_divss",
    "helper_divsd",
    "helper_minps_xmm",
    "helper_minpd_xmm",
    "helper_minss",
    "helper_minsd",
    "helper_maxps_xmm",
    "helper_maxpd_xmm",
    "helper_maxss",
    "helper_maxsd",
    "helper_sqrtps_xmm",
    "helper_sqrtpd_xmm",
    "helper_sqrtss",
    "helper_sqrtsd",
    "helper_cvtps2pd_xmm",
    "helper_cvtpd2ps_xmm",
    "helper_cvtdq2ps_xmm",
    "helper_cvtdq2pd_xmm",
    "helper_cvtps2dq_xmm",
    "helper_cvtpd2dq_xmm",
    "helper_cvttps2dq_xmm",
    "helper_cvttpd2dq_xmm",
    "helper_cvtss2sd",
    "helper_cvtsd2ss",
    "helper_cvtpi2ps",
    "helper_cvtpi2pd",
    "helper_cvtsi2ss",
    "helper_cvtsi2sd",
    "helper_cvtsq2ss",
    "helper_cvtsq2sd",
    "helper_cvtps2pi",
    "helper_cvtpd2pi",
    "helper_cvtss2si",
    "helper_cvtsd2si",
    "helper_cvtss2sq",
    "helper_cvtsd2sq",
    "helper_cvttps2pi",
    "helper_cvttpd2pi",
    "helper_cvttss2si",
    "helper_cvttsd2si",
    "helper_cvttss2sq",
    "helper_cvttsd2sq",
    "helper_rsqrtps_xmm",
    "helper_rcpps_xmm",
    "helper_rsqrtss",
    "helper_rcpss",
    "helper_extrq_r",
    "helper_extrq_i",
    "helper_insertq_r",
    "helper_insertq_i",
    "helper_haddps_xmm",
    "helper_haddpd_xmm",
    "helper_hsubps_xmm",
    "helper_hsubpd_xmm",
    "helper_addsubps_xmm",
    "helper_addsubpd_xmm",
    "helper_cmpeqps_xmm",
    "helper_cmpeqpd_xmm",
    "helper_cmpeqss",
    "helper_cmpeqsd",
    "helper_cmpltps_xmm",
    "helper_cmpltpd_xmm",
    "helper_cmpltss",
    "helper_cmpltsd",
    "helper_cmpleps_xmm",
    "helper_cmplepd_xmm",
    "helper_cmpless",
    "helper_cmplesd",
    "helper_cmpunordps_xmm",
    "helper_cmpunordpd_xmm",
    "helper_cmpunordss",
    "helper_cmpunordsd",
    "helper_cmpneqps_xmm",
    "helper_cmpneqpd_xmm",
    "helper_cmpneqss",
    "helper_cmpneqsd",
    "helper_cmpnltps_xmm",
    "helper_cmpnltpd_xmm",
    "helper_cmpnltss",
    "helper_cmpnltsd",
    "helper_cmpnleps_xmm",
    "helper_cmpnlepd_xmm",
    "helper_cmpnless",
    "helper_cmpnlesd",
    "helper_cmpordps_xmm",
    "helper_cmpordpd_xmm",
    "helper_cmpordss",
    "helper_cmpordsd",
    "helper_cmpequps_xmm",
    "helper_cmpequpd_xmm",
    "helper_cmpequss",
    "helper_cmpequsd",
    "helper_cmpngeps_xmm",
    "helper_cmpngepd_xmm",
    "helper_cmpngess",
    "helper_cmpngesd",
    "helper_cmpngtps_xmm",
    "helper_cmpngtpd_xmm",
    "helper_cmpngtss",
    "helper_cmpngtsd",
    "helper_cmpfalseps_xmm",
    "helper_cmpfalsepd_xmm",
    "helper_cmpfalsess",
    "helper_cmpfalsesd",
    "helper_cmpnequps_xmm",
    "helper_cmpnequpd_xmm",
    "helper_cmpnequss",
    "helper_cmpnequsd",
    "helper_cmpgeps_xmm",
    "helper_cmpgepd_xmm",
    "helper_cmpgess",
    "helper_cmpgesd",
    "helper_cmpgtps_xmm",
    "helper_cmpgtpd_xmm",
    "helper_cmpgtss",
    "helper_cmpgtsd",
    "helper_cmptrueps_xmm",
    "helper_cmptruepd_xmm",
    "helper_cmptruess",
    "helper_cmptruesd",
    "helper_cmpeqsps_xmm",
    "helper_cmpeqspd_xmm",
    "helper_cmpeqsss",
    "helper_cmpeqssd",
    "helper_cmpltqps_xmm",
    "helper_cmpltqpd_xmm",
    "helper_cmpltqss",
    "helper_cmpltqsd",
    "helper_cmpleqps_xmm",
    "helper_cmpleqpd_xmm",
    "helper_cmpleqss",
    "helper_cmpleqsd",
    "helper_cmpunordsps_xmm",
    "helper_cmpunordspd_xmm",
    "helper_cmpunordsss",
    "helper_cmpunordssd",
    "helper_cmpneqqps_xmm",
    "helper_cmpneqqpd_xmm",
    "helper_cmpneqqss",
    "helper_cmpneqqsd",
    "helper_cmpnltqps_xmm",
    "helper_cmpnltqpd_xmm",
    "helper_cmpnltqss",
    "helper_cmpnltqsd",
    "helper_cmpnleqps_xmm",
    "helper_cmpnleqpd_xmm",
    "helper_cmpnleqss",
    "helper_cmpnleqsd",
    "helper_cmpordsps_xmm",
    "helper_cmpordspd_xmm",
    "helper_cmpordsss",
    "helper_cmpordssd",
    "helper_cmpequsps_xmm",
    "helper_cmpequspd_xmm",
    "helper_cmpequsss",
    "helper_cmpequssd",
    "helper_cmpngeqps_xmm",
    "helper_cmpngeqpd_xmm",
    "helper_cmpngeqss",
    "helper_cmpngeqsd",
    "helper_cmpngtqps_xmm",
    "helper_cmpngtqpd_xmm",
    "helper_cmpngtqss",
    "helper_cmpngtqsd",
    "helper_cmpfalsesps_xmm",
    "helper_cmpfalsespd_xmm",
    "helper_cmpfalsesss",
    "helper_cmpfalsessd",
    "helper_cmpnequsps_xmm",
    "helper_cmpnequspd_xmm",
    "helper_cmpnequsss",
    "helper_cmpnequssd",
    "helper_cmpgeqps_xmm",
    "helper_cmpgeqpd_xmm",
    "helper_cmpgeqss",
    "helper_cmpgeqsd",
    "helper_cmpgtqps_xmm",
    "helper_cmpgtqpd_xmm",
    "helper_cmpgtqss",
    "helper_cmpgtqsd",
    "helper_cmptruesps_xmm",
    "helper_cmptruespd_xmm",
    "helper_cmptruesss",
    "helper_cmptruessd",
    "helper_ucomiss",
    "helper_comiss",
    "helper_ucomisd",
    "helper_comisd",
    "helper_movmskps_xmm",
    "helper_movmskpd_xmm",
    "helper_packsswb_xmm",
    "helper_packuswb_xmm",
    "helper_packssdw_xmm",
    "helper_punpcklbw_xmm",
    "helper_punpcklwd_xmm",
    "helper_punpckldq_xmm",
    "helper_punpckhbw_xmm",
    "helper_punpckhwd_xmm",
    "helper_punpckhdq_xmm",
    "helper_punpcklqdq_xmm",
    "helper_punpckhqdq_xmm",
    "helper_phaddw_xmm",
    "helper_phaddd_xmm",
    "helper_phaddsw_xmm",
    "helper_phsubw_xmm",
    "helper_phsubd_xmm",
    "helper_phsubsw_xmm",
    "helper_pmaddubsw_xmm",
    "helper_pmulhrsw_xmm",
    "helper_pshufb_xmm",
    "helper_psignb_xmm",
    "helper_psignw_xmm",
    "helper_psignd_xmm",
    "helper_palignr_xmm",
    "helper_pblendvb_xmm",
    "helper_blendvps_xmm",
    "helper_blendvpd_xmm",
    "helper_ptest_xmm",
    "helper_pmovsxbw_xmm",
    "helper_pmovsxbd_xmm",
    "helper_pmovsxbq_xmm",
    "helper_pmovsxwd_xmm",
    "helper_pmovsxwq_xmm",
    "helper_pmovsxdq_xmm",
    "helper_pmovzxbw_xmm",
    "helper_pmovzxbd_xmm",
    "helper_pmovzxbq_xmm",
    "helper_pmovzxwd_xmm",
    "helper_pmovzxwq_xmm",
    "helper_pmovzxdq_xmm",
    "helper_pmovsldup_xmm",
    "helper_pmovshdup_xmm",
    "helper_pmovdldup_xmm",
    "helper_pmuldq_xmm",
    "helper_packusdw_xmm",
    "helper_phminposuw_xmm",
    "helper_roundps_xmm",
    "helper_roundpd_xmm",
    "helper_roundss_xmm",
    "helper_roundsd_xmm",
    "helper_blendps_xmm",
    "helper_blendpd_xmm",
    "helper_pblendw_xmm",
    "helper_dpps_xmm",
    "helper_dppd_xmm",
    "helper_mpsadbw_xmm",
    "helper_pcmpestri_xmm",
    "helper_pcmpestrm_xmm",
    "helper_pcmpistri_xmm",
    "helper_pcmpistrm_xmm",
    "helper_crc32",
    "helper_aesdec_xmm",
    "helper_aesdeclast_xmm",
    "helper_aesenc_xmm",
    "helper_aesenclast_xmm",
    "helper_aesimc_xmm",
    "helper_aeskeygenassist_xmm",
    "helper_pclmulqdq_xmm",
    "helper_cvtph2ps_xmm",
    "helper_cvtps2ph_xmm",
    "helper_fma4ss",
    "helper_fma4sd",
    "helper_fma4ps_xmm",
    "helper_fma4pd_xmm",
    "helper_vpermilpd_xmm",
    "helper_vpermilps_xmm",
    "helper_vpermilpd_imm_xmm",
    "helper_vpermilps_imm_xmm",
    "helper_vpsrlvd_xmm",
    "helper_vpsravd_xmm",
    "helper_vpsllvd_xmm",
    "helper_vpsrlvq_xmm",
    "helper_vpsravq_xmm",
    "helper_vpsllvq_xmm",
    "helper_vtestps_xmm",
    "helper_vtestpd_xmm",
    "helper_vpmaskmovd_st_xmm",
    "helper_vpmaskmovq_st_xmm",
    "helper_vpmaskmovd_xmm",
    "helper_vpmaskmovq_xmm",
    "helper_vpgatherdd_xmm",
    "helper_vpgatherdq_xmm",
    "helper_vpgatherqd_xmm",
    "helper_vpgatherqq_xmm",
    "helper_sha1rnds4_f0",
    "helper_sha1rnds4_f1",
    "helper_sha1rnds4_f2",
    "helper_sha1rnds4_f3",
    "helper_sha1nexte",
    "helper_sha1msg1",
    "helper_sha1msg2",
    "helper_sha256rnds2",
    "helper_sha256msg1",
    "helper_sha256msg2",
    "helper_psrlw_ymm",
    "helper_psraw_ymm",
    "helper_psllw_ymm",
    "helper_psrld_ymm",
    "helper_psrad_ymm",
    "helper_pslld_ymm",
    "helper_psrlq_ymm",
    "helper_psllq_ymm",
    "helper_psrldq_ymm",
    "helper_pslldq_ymm",
    "helper_pmulhuw_ymm",
    "helper_pmulhw_ymm",
    "helper_pavgb_ymm",
    "helper_pavgw_ymm",
    "helper_pmuludq_ymm",
    "helper_pmaddwd_ymm",
    "helper_psadbw_ymm",
    "helper_pshufd_ymm",
    "helper_pshuflw_ymm",
    "helper_pshufhw_ymm",
    "helper_shufps_ymm",
    "helper_shufpd_ymm",
    "helper_addps_ymm",
    "helper_addpd_ymm",
    "helper_subps_ymm",
    "helper_subpd_ymm",
    "helper_mulps_ymm",
    "helper_mulpd_ymm",
    "helper_divps_ymm",
    "helper_divpd_ymm",
    "helper_minps_ymm",
    "helper_minpd_ymm",
    "helper_maxps_ymm",
    "helper_maxpd_ymm",
    "helper_sqrtps_ymm",
    "helper_sqrtpd_ymm",
    "helper_cvtps2pd_ymm",
    "helper_cvtpd2ps_ymm",
    "helper_cvtdq2ps_ymm",
    "helper_cvtdq2pd_ymm",
    "helper_cvtps2dq_ymm",
    "helper_cvtpd2dq_ymm",
    "helper_cvttps2dq_ymm",
    "helper_cvttpd2dq_ymm",
    "helper_rsqrtps_ymm",
    "helper_rcpps_ymm",
    "helper_haddps_ymm",
    "helper_haddpd_ymm",
    "helper_hsubps_ymm",
    "helper_hsubpd_ymm",
    "helper_addsubps_ymm",
    "helper_addsubpd_ymm",
    "helper_cmpeqps_ymm",
    "helper_cmpeqpd_ymm",
    "helper_cmpltps_ymm",
    "helper_cmpltpd_ymm",
    "helper_cmpleps_ymm",
    "helper_cmplepd_ymm",
    "helper_cmpunordps_ymm",
    "helper_cmpunordpd_ymm",
    "helper_cmpneqps_ymm",
    "helper_cmpneqpd_ymm",
    "helper_cmpnltps_ymm",
    "helper_cmpnltpd_ymm",
    "helper_cmpnleps_ymm",
    "helper_cmpnlepd_ymm",
    "helper_cmpordps_ymm",
    "helper_cmpordpd_ymm",
    "helper_cmpequps_ymm",
    "helper_cmpequpd_ymm",
    "helper_cmpngeps_ymm",
    "helper_cmpngepd_ymm",
    "helper_cmpngtps_ymm",
    "helper_cmpngtpd_ymm",
    "helper_cmpfalseps_ymm",
    "helper_cmpfalsepd_ymm",
    "helper_cmpnequps_ymm",
    "helper_cmpnequpd_ymm",
    "helper_cmpgeps_ymm",
    "helper_cmpgepd_ymm",
    "helper_cmpgtps_ymm",
    "helper_cmpgtpd_ymm",
    "helper_cmptrueps_ymm",
    "helper_cmptruepd_ymm",
    "helper_cmpeqsps_ymm",
    "helper_cmpeqspd_ymm",
    "helper_cmpltqps_ymm",
    "helper_cmpltqpd_ymm",
    "helper_cmpleqps_ymm",
    "helper_cmpleqpd_ymm",
    "helper_cmpunordsps_ymm",
    "helper_cmpunordspd_ymm",
    "helper_cmpneqqps_ymm",
    "helper_cmpneqqpd_ymm",
    "helper_cmpnltqps_ymm",
    "helper_cmpnltqpd_ymm",
    "helper_cmpnleqps_ymm",
    "helper_cmpnleqpd_ymm",
    "helper_cmpordsps_ymm",
    "helper_cmpordspd_ymm",
    "helper_cmpequsps_ymm",
    "helper_cmpequspd_ymm",
    "helper_cmpngeqps_ymm",
    "helper_cmpngeqpd_ymm",
    "helper_cmpngtqps_ymm",
    "helper_cmpngtqpd_ymm",
    "helper_cmpfalsesps_ymm",
    "helper_cmpfalsespd_ymm",
    "helper_cmpnequsps_ymm",
    "helper_cmpnequspd_ymm",
    "helper_cmpgeqps_ymm",
    "helper_cmpgeqpd_ymm",
    "helper_cmpgtqps_ymm",
    "helper_cmpgtqpd_ymm",
    "helper_cmptruesps_ymm",
    "helper_cmptruespd_ymm",
    "helper_movmskps_ymm",
    "helper_movmskpd_ymm",
    "helper_packsswb_ymm",
    "helper_packuswb_ymm",
    "helper_packssdw_ymm",
    "helper_punpcklbw_ymm",
    "helper_punpcklwd_ymm",
    "helper_punpckldq_ymm",
    "helper_punpckhbw_ymm",
    "helper_punpckhwd_ymm",
    "helper_punpckhdq_ymm",
    "helper_punpcklqdq_ymm",
    "helper_punpckhqdq_ymm",
    "helper_phaddw_ymm",
    "helper_phaddd_ymm",
    "helper_phaddsw_ymm",
    "helper_phsubw_ymm",
    "helper_phsubd_ymm",
    "helper_phsubsw_ymm",
    "helper_pmaddubsw_ymm",
    "helper_pmulhrsw_ymm",
    "helper_pshufb_ymm",
    "helper_psignb_ymm",
    "helper_psignw_ymm",
    "helper_psignd_ymm",
    "helper_palignr_ymm",
    "helper_pblendvb_ymm",
    "helper_blendvps_ymm",
    "helper_blendvpd_ymm",
    "helper_ptest_ymm",
    "helper_pmovsxbw_ymm",
    "helper_pmovsxbd_ymm",
    "helper_pmovsxbq_ymm",
    "helper_pmovsxwd_ymm",
    "helper_pmovsxwq_ymm",
    "helper_pmovsxdq_ymm",
    "helper_pmovzxbw_ymm",
    "helper_pmovzxbd_ymm",
    "helper_pmovzxbq_ymm",
    "helper_pmovzxwd_ymm",
    "helper_pmovzxwq_ymm",
    "helper_pmovzxdq_ymm",
    "helper_pmovsldup_ymm",
    "helper_pmovshdup_ymm",
    "helper_pmovdldup_ymm",
    "helper_pmuldq_ymm",
    "helper_packusdw_ymm",
    "helper_roundps_ymm",
    "helper_roundpd_ymm",
    "helper_blendps_ymm",
    "helper_blendpd_ymm",
    "helper_pblendw_ymm",
    "helper_dpps_ymm",
    "helper_mpsadbw_ymm",
    "helper_aesdec_ymm",
    "helper_aesdeclast_ymm",
    "helper_aesenc_ymm",
    "helper_aesenclast_ymm",
    "helper_pclmulqdq_ymm",
    "helper_cvtph2ps_ymm",
    "helper_cvtps2ph_ymm",
    "helper_fma4ps_ymm",
    "helper_fma4pd_ymm",
    "helper_vpermilpd_ymm",
    "helper_vpermilps_ymm",
    "helper_vpermilpd_imm_ymm",
    "helper_vpermilps_imm_ymm",
    "helper_vpsrlvd_ymm",
    "helper_vpsravd_ymm",
    "helper_vpsllvd_ymm",
    "helper_vpsrlvq_ymm",
    "helper_vpsravq_ymm",
    "helper_vpsllvq_ymm",
    "helper_vtestps_ymm",
    "helper_vtestpd_ymm",
    "helper_vpmaskmovd_st_ymm",
    "helper_vpmaskmovq_st_ymm",
    "helper_vpmaskmovd_ymm",
    "helper_vpmaskmovq_ymm",
    "helper_vpgatherdd_ymm",
    "helper_vpgatherdq_ymm",
    "helper_vpgatherqd_ymm",
    "helper_vpgatherqq_ymm",
    "helper_vpermd_ymm",
    "helper_vpermdq_ymm",
    "helper_vpermq_ymm",
    "helper_rdrand",
    "helper_dump_registers",
    "helper_dump_load",
    "helper_dump_store",
};

/* Verify a hash result by checking the name at that slot.
 * Returns 1 if hash is correct, 0 otherwise.
 */
static inline int helper_hash_verify(const char *name, int32_t slot)
{
    if (slot < 0 || slot >= HELPER_HASH_N) return 0;
    return (strcmp(name, helper_names[slot]) == 0);
}

int main(void)
{
    int seen[HELPER_HASH_N];
    memset(seen, 0, sizeof(seen));
    int errors = 0;
    int collisions = 0;

    for (int i = 0; i < HELPER_HASH_N; i++) {
        int slot = helper_name_hash(helper_names[i]);

        if (slot < 0 || slot >= HELPER_HASH_N) {
            printf("ERROR: %%s -> slot %%d out of range\n", helper_names[i], slot);
            errors++;
            continue;
        }

        if (seen[slot]) {
            printf("COLLISION: %%s and %%s both hash to %%d\n",
                   helper_names[i], helper_names[seen[slot]-1], slot);
            collisions++;
            errors++;
        }

        seen[slot] = i + 1;
    }

    int unique = 0;
    for (int i = 0; i < HELPER_HASH_N; i++) {
        if (seen[i]) unique++;
    }

    printf("\n");
    printf("╔══════════════════════════════════════════════════════╗\n");
    printf("║  Minimal Perfect Hash — Verification Report          ║\n");
    printf("╠══════════════════════════════════════════════════════╣\n");
    printf("║  Total names:       %-33d ║\n", HELPER_HASH_N);
    printf("║  Unique slots used: %-33d ║\n", unique);
    printf("║  Table size:        %-33d ║\n", HELPER_HASH_N);
    printf("║  Overhead:          %-33d ║\n", HELPER_HASH_N - unique);
    printf("║  Overhead %%:        %-32.1f%% ║\n", 0.0);
    printf("║  Collisions:        %-33d ║\n", collisions);
    printf("║  Errors:            %-33d ║\n", errors);
    printf("╚══════════════════════════════════════════════════════╝\n");

    if (errors == 0) {
        printf("\n✅ SUCCESS: All %d names hash to unique slots!\n", HELPER_HASH_N);
        printf("   Table utilization: 100%% (MINIMAL)\n");
        return 0;
    } else {
        printf("\n❌ FAILED: %d errors found\n", errors);
        return 1;
    }
}
