#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <string.h>
#include "tcg_ast.h"

const char *opcode_type_str[] = {
    #define X(name) #name,
    OPCODE_TYPE_LIST
    #undef X
};

const char *attr_type_str[] = {
    #define X(name) #name,
    ATTR_TYPE_LIST
    #undef X
};

const char *envvar_type_str[] = {
    #define X(name) #name,
    ENVVAR_TYPE_LIST
    #undef X
};

const char *xreg_type_str[] = {
    #define X(name) #name,
    XREG_TYPE_LIST
    #undef X
};

const char *relop_type_str[] = {
    #define X(name) #name,
    RELOP_TYPE_LIST
    #undef X
};

const char *helper_str[] = {
    #define X(name) #name,
    HELPER_LIST
    #undef X
};

const char *alignment_type_str[] = {
    #define X(name) #name,
    ALIGNMENT_TYPE_LIST
    #undef X
};

const char *srcext_type_str[] = {
    #define X(name) #name,
    SRCEXT_TYPE_LIST
    #undef X
};

const char *slot_type_str[] = {
    #define X(name) #name,
    SLOT_TYPE_LIST
    #undef X
};

const char *llvm_type_str[] = {
    #define X(name) #name,
    LLVM_TYPE_LIST
    #undef X
};

const char *xmmreg_str[] = {
    #define X(name) #name,
    XMM_REG_LIST
    #undef X
};

const char *cvector_str[] = {
    #define X(name) #name,
    C_VECTOR_TYPE
    #undef X
};

const uint8_t opcoc[OPCODE_MAX] = {
    [addci_i32] = 1,
    [addci_i64] = 1,
    [addcio_i32] = 1,
    [addcio_i64] = 1,
    [addco_i32] = 1,
    [addco_i64] = 1,
    [subbi_i32] = 1,
    [subbi_i64] = 1,
    [subbio_i32] = 1,
    [subbio_i64] = 1,
    [subbo_i32] = 1,
    [subbo_i64] = 1,
    [abs_vec] = 1,
    [add_i32] = 1,
    [add_i64] = 1,
    [add_vec] = 1,
    [andc_i32] = 1,
    [andc_i64] = 1,
    [andc_vec] = 1,
    [and_i32] = 1,
    [and_i64] = 1,
    [and_vec] = 1,
    [bitsel_vec] = 1,
    [bswap16_i32] = 1,
    [bswap16_i64] = 1,
    [bswap32_i32] = 1,
    [bswap32_i64] = 1,
    [bswap64_i64] = 1,
    [clz_i32] = 1,
    [clz_i64] = 1,
    [cmpsel_vec] = 1,
    [cmp_vec] = 1,
    [ctpop_i32] = 1,
    [ctpop_i64] = 1,
    [ctz_i32] = 1,
    [ctz_i64] = 1,
    [deposit_i32] = 1,
    [deposit_i64] = 1,
    [divs2_i32] = 2,
    [divs2_i64] = 2,
    [divs_i32] = 1,
    [divs_i64] = 1,
    [divu2_i32] = 2,
    [divu2_i64] = 2,
    [divu_i32] = 1,
    [divu_i64] = 1,
    [dupm_vec] = 1,
    [dup_vec] = 1,
    [eqv_i32] = 1,
    [eqv_i64] = 1,
    [eqv_vec] = 1,
    [ext_i32_i64] = 1,
    [extract2_i32] = 1,
    [extract2_i64] = 1,
    [extract_i32] = 1,
    [extract_i64] = 1,
    [extrh_i64_i32] = 1,
    [extrl_i64_i32] = 1,
    [extu_i32_i64] = 1,
    [ld16s_i32] = 1,
    [ld16s_i64] = 1,
    [ld16u_i32] = 1,
    [ld16u_i64] = 1,
    [ld32s_i64] = 1,
    [ld32u_i64] = 1,
    [ld8s_i32] = 1,
    [ld8s_i64] = 1,
    [ld8u_i32] = 1,
    [ld8u_i64] = 1,
    [ld_i32] = 1,
    [ld_i64] = 1,
    [ld_vec] = 1,
    [movcond_i32] = 1,
    [movcond_i64] = 1,
    [movcond_vec] = 1,
    [mov_i32] = 1,
    [mov_i64] = 1,
    [mov_vec] = 1,
    [mul_i32] = 1,
    [mul_i64] = 1,
    [muls2_i32] = 2,
    [muls2_i64] = 2,
    [mulsh_i32] = 1,
    [mulsh_i64] = 1,
    [mulu2_i32] = 2,
    [mulu2_i64] = 2,
    [muluh_i32] = 1,
    [muluh_i64] = 1,
    [mul_vec] = 1,
    [nand_i32] = 1,
    [nand_i64] = 1,
    [nand_vec] = 1,
    [neg_i32] = 1,
    [neg_i64] = 1,
    [negsetcond_i32] = 1,
    [negsetcond_i64] = 1,
    [neg_vec] = 1,
    [nor_i32] = 1,
    [nor_i64] = 1,
    [nor_vec] = 1,
    [not_i32] = 1,
    [not_i64] = 1,
    [not_vec] = 1,
    [orc_i32] = 1,
    [orc_i64] = 1,
    [orc_vec] = 1,
    [or_i32] = 1,
    [or_i64] = 1,
    [or_vec] = 1,
    [qemu_ld2_i128] = 2,
    [qemu_ld_i32] = 1,
    [qemu_ld_i64] = 1,
    [rems_i32] = 1,
    [rems_i64] = 1,
    [remu_i32] = 1,
    [remu_i64] = 1,
    [rotl_i32] = 1,
    [rotl_i64] = 1,
    [rotli_vec] = 1,
    [rotls_vec] = 1,
    [rotlv_vec] = 1,
    [rotr_i32] = 1,
    [rotr_i64] = 1,
    [rotrv_vec] = 1,
    [sar_i32] = 1,
    [sar_i64] = 1,
    [sari_vec] = 1,
    [sars_vec] = 1,
    [sarv_vec] = 1,
    [setcond_i32] = 1,
    [setcond_i64] = 1,
    [sextract_i32] = 1,
    [sextract_i64] = 1,
    [shl_i32] = 1,
    [shl_i64] = 1,
    [shli_vec] = 1,
    [shls_vec] = 1,
    [shlv_vec] = 1,
    [shr_i32] = 1,
    [shr_i64] = 1,
    [shri_vec] = 1,
    [shrs_vec] = 1,
    [shrv_vec] = 1,
    [smax_vec] = 1,
    [smin_vec] = 1,
    [ssadd_vec] = 1,
    [sssub_vec] = 1,
    [sub_i32] = 1,
    [sub_i64] = 1,
    [sub_vec] = 1,
    [umax_vec] = 1,
    [umin_vec] = 1,
    [usadd_vec] = 1,
    [ussub_vec] = 1,
    [xor_i32] = 1,
    [xor_i64] = 1,
    [xor_vec] = 1,
};

const int helper_require_exception_path[HELPER_MAX] = {
    [helper_cc_compute_nz] = 1,
    [helper_addps_xmm] = 1,
    [helper_minps_xmm] = 1,
    [helper_cmpltps_xmm] = 1,
    [helper_addsubps_xmm] = 1,
    [helper_cmpltqps_xmm] = 1,
    [helper_vpgatherdq_xmm] = 1,
    [helper_cmpnlepd_xmm] = 1,
    [helper_cmpnequps_xmm] = 1,
    [helper_cmptrueps_xmm] = 1,
    [helper_cmpngtpd_xmm] = 1,
    [helper_cmpneqpd_xmm] = 1,
    [helper_aesdec_xmm] = 1,
    [helper_cmpfalsepd_xmm] = 1,
    [helper_cmpfalsespd_xmm] = 1,
    [helper_cmpngtps_xmm] = 1,
    [helper_cvttpd2dq_xmm] = 1,
    [helper_cmpltpd_xmm] = 1,
    [helper_mulps_xmm] = 1,
    [helper_cvtps2dq_xmm] = 1,
    [helper_cmpfalseps_xmm] = 1,
    [helper_cmpnleqpd_xmm] = 1,
    [helper_cmpneqps_xmm] = 1,
    [helper_cmpngtqpd_xmm] = 1,
    [helper_cmpltqpd_xmm] = 1,
    [helper_addsubpd_xmm] = 1,
    [helper_aesenc_xmm] = 1,
    [helper_cvtph2ps_xmm] = 1,
    [helper_sqrtpd_xmm] = 1,
    [helper_vpmaskmovq_st_xmm] = 1,
    [helper_cmpnleps_xmm] = 1,
    [helper_cmpneqqpd_xmm] = 1,
    [helper_cvtps2ph_xmm] = 1,
    [helper_cmpunordsps_xmm] = 1,
    [helper_fma4ps_xmm] = 1,
    [helper_hsubps_xmm] = 1,
    [helper_cmpordsps_xmm] = 1,
    [helper_cmpequsps_xmm] = 1,
    [helper_mulpd_xmm] = 1,
    [helper_cmpnltpd_xmm] = 1,
    [helper_cvtpd2dq_xmm] = 1,
    [helper_cmpeqpd_xmm] = 1,
    [helper_cmpngepd_xmm] = 1,
    [helper_roundss_xmm] = 1,
    [helper_dppd_xmm] = 1,
    [helper_cmpgeps_xmm] = 1,
    [helper_cmpgeqps_xmm] = 1,
    [helper_aesdeclast_xmm] = 1,
    [helper_cmpngeps_xmm] = 1,
    [helper_haddpd_xmm] = 1,
    [helper_minpd_xmm] = 1,
    [helper_cmpgeqpd_xmm] = 1,
    [helper_cmpnltqpd_xmm] = 1,
    [helper_cmpeqps_xmm] = 1,
    [helper_addpd_xmm] = 1,
    [helper_vpgatherqq_xmm] = 1,
    [helper_roundsd_xmm] = 1,
    [helper_aesimc_xmm] = 1,
    [helper_aesenclast_xmm] = 1,
    [helper_cmpngeqpd_xmm] = 1,
    [helper_maskmov_xmm] = 1,
    [helper_cmpnltps_xmm] = 1,
    [helper_cmpgepd_xmm] = 1,
    [helper_pclmulqdq_xmm] = 1,
    [helper_cmpordpd_xmm] = 1,
    [helper_cmpnequpd_xmm] = 1,
    [helper_cmplepd_xmm] = 1,
    [helper_cmpequpd_xmm] = 1,
    [helper_haddps_xmm] = 1,
    [helper_dpps_xmm] = 1,
    [helper_cmpleqpd_xmm] = 1,
    [helper_vpmaskmovd_st_xmm] = 1,
    [helper_cmpeqsps_xmm] = 1,
    [helper_cmptruepd_xmm] = 1,
    [helper_rcpps_xmm] = 1,
    [helper_divps_xmm] = 1,
    [helper_vpgatherdd_xmm] = 1,
    [helper_subpd_xmm] = 1,
    [helper_cmpleqps_xmm] = 1,
    [helper_cmpnleqps_xmm] = 1,
    [helper_cmpleps_xmm] = 1,
    [helper_maxpd_xmm] = 1,
    [helper_fma4pd_xmm] = 1,
    [helper_cmpeqspd_xmm] = 1,
    [helper_hsubpd_xmm] = 1,
    [helper_cvtpd2ps_xmm] = 1,
    [helper_cmpneqqps_xmm] = 1,
    [helper_cmpordps_xmm] = 1,
    [helper_cmpequps_xmm] = 1,
    [helper_cmpngtqps_xmm] = 1,
    [helper_cmptruesps_xmm] = 1,
    [helper_cmpfalsesps_xmm] = 1,
    [helper_cmpequspd_xmm] = 1,
    [helper_cmpordspd_xmm] = 1,
    [helper_subps_xmm] = 1,
    [helper_cvttps2dq_xmm] = 1,
    [helper_maxps_xmm] = 1,
    [helper_cmpgtqpd_xmm] = 1,
    [helper_roundps_xmm] = 1,
    [helper_cmpunordps_xmm] = 1,
    [helper_cvtdq2pd_xmm] = 1,
    [helper_vpgatherqd_xmm] = 1,
    [helper_cmpnequsps_xmm] = 1,
    [helper_cmpunordspd_xmm] = 1,
    [helper_sqrtps_xmm] = 1,
    [helper_cmpgtpd_xmm] = 1,
    [helper_cvtdq2ps_xmm] = 1,
    [helper_cmpnltqps_xmm] = 1,
    [helper_cmpunordpd_xmm] = 1,
    [helper_cmpnequspd_xmm] = 1,
    [helper_rsqrtps_xmm] = 1,
    [helper_cmptruespd_xmm] = 1,
    [helper_divpd_xmm] = 1,
    [helper_cvtps2pd_xmm] = 1,
    [helper_roundpd_xmm] = 1,
    [helper_cmpngeqps_xmm] = 1,
    [helper_cmpgtqps_xmm] = 1,
    [helper_cmpgtps_xmm] = 1,
    [helper_addpd_ymm] = 1,
    [helper_addps_ymm] = 1,
    [helper_addsubpd_ymm] = 1,
    [helper_addsubps_ymm] = 1,
    [helper_aesdeclast_ymm] = 1,
    [helper_aesdec_ymm] = 1,
    [helper_aesenclast_ymm] = 1,
    [helper_aesenc_ymm] = 1,
    [helper_cmpeqpd_ymm] = 1,
    [helper_cmpeqps_ymm] = 1,
    [helper_cmpeqspd_ymm] = 1,
    [helper_cmpeqsps_ymm] = 1,
    [helper_cmpequpd_ymm] = 1,
    [helper_cmpequps_ymm] = 1,
    [helper_cmpequspd_ymm] = 1,
    [helper_cmpequsps_ymm] = 1,
    [helper_cmpfalsepd_ymm] = 1,
    [helper_cmpfalseps_ymm] = 1,
    [helper_cmpfalsespd_ymm] = 1,
    [helper_cmpfalsesps_ymm] = 1,
    [helper_cmpgepd_ymm] = 1,
    [helper_cmpgeps_ymm] = 1,
    [helper_cmpgeqpd_ymm] = 1,
    [helper_cmpgeqps_ymm] = 1,
    [helper_cmpgtpd_ymm] = 1,
    [helper_cmpgtps_ymm] = 1,
    [helper_cmpgtqpd_ymm] = 1,
    [helper_cmpgtqps_ymm] = 1,
    [helper_cmplepd_ymm] = 1,
    [helper_cmpleps_ymm] = 1,
    [helper_cmpleqpd_ymm] = 1,
    [helper_cmpleqps_ymm] = 1,
    [helper_cmpltpd_ymm] = 1,
    [helper_cmpltps_ymm] = 1,
    [helper_cmpltqpd_ymm] = 1,
    [helper_cmpltqps_ymm] = 1,
    [helper_cmpneqpd_ymm] = 1,
    [helper_cmpneqps_ymm] = 1,
    [helper_cmpneqqpd_ymm] = 1,
    [helper_cmpneqqps_ymm] = 1,
    [helper_cmpnequpd_ymm] = 1,
    [helper_cmpnequps_ymm] = 1,
    [helper_cmpnequspd_ymm] = 1,
    [helper_cmpnequsps_ymm] = 1,
    [helper_cmpngepd_ymm] = 1,
    [helper_cmpngeps_ymm] = 1,
    [helper_cmpngeqpd_ymm] = 1,
    [helper_cmpngeqps_ymm] = 1,
    [helper_cmpngtpd_ymm] = 1,
    [helper_cmpngtps_ymm] = 1,
    [helper_cmpngtqpd_ymm] = 1,
    [helper_cmpngtqps_ymm] = 1,
    [helper_cmpnlepd_ymm] = 1,
    [helper_cmpnleps_ymm] = 1,
    [helper_cmpnleqpd_ymm] = 1,
    [helper_cmpnleqps_ymm] = 1,
    [helper_cmpnltpd_ymm] = 1,
    [helper_cmpnltps_ymm] = 1,
    [helper_cmpnltqpd_ymm] = 1,
    [helper_cmpnltqps_ymm] = 1,
    [helper_cmpordpd_ymm] = 1,
    [helper_cmpordps_ymm] = 1,
    [helper_cmpordspd_ymm] = 1,
    [helper_cmpordsps_ymm] = 1,
    [helper_cmptruepd_ymm] = 1,
    [helper_cmptrueps_ymm] = 1,
    [helper_cmptruespd_ymm] = 1,
    [helper_cmptruesps_ymm] = 1,
    [helper_cmpunordpd_ymm] = 1,
    [helper_cmpunordps_ymm] = 1,
    [helper_cmpunordspd_ymm] = 1,
    [helper_cmpunordsps_ymm] = 1,
    [helper_cvtdq2pd_ymm] = 1,
    [helper_cvtdq2ps_ymm] = 1,
    [helper_cvtpd2dq_ymm] = 1,
    [helper_cvtpd2ps_ymm] = 1,
    [helper_cvtph2ps_ymm] = 1,
    [helper_cvtps2dq_ymm] = 1,
    [helper_cvtps2pd_ymm] = 1,
    [helper_cvtps2ph_ymm] = 1,
    [helper_cvttpd2dq_ymm] = 1,
    [helper_cvttps2dq_ymm] = 1,
    [helper_divpd_ymm] = 1,
    [helper_divps_ymm] = 1,
    [helper_dpps_ymm] = 1,
    [helper_fma4pd_ymm] = 1,
    [helper_fma4ps_ymm] = 1,
    [helper_haddpd_ymm] = 1,
    [helper_haddps_ymm] = 1,
    [helper_hsubpd_ymm] = 1,
    [helper_hsubps_ymm] = 1,
    [helper_maxpd_ymm] = 1,
    [helper_maxps_ymm] = 1,
    [helper_minpd_ymm] = 1,
    [helper_minps_ymm] = 1,
    [helper_mulpd_ymm] = 1,
    [helper_mulps_ymm] = 1,
    [helper_pclmulqdq_ymm] = 1,
    [helper_rcpps_ymm] = 1,
    [helper_roundpd_ymm] = 1,
    [helper_roundps_ymm] = 1,
    [helper_rsqrtps_ymm] = 1,
    [helper_sqrtpd_ymm] = 1,
    [helper_sqrtps_ymm] = 1,
    [helper_subpd_ymm] = 1,
    [helper_subps_ymm] = 1,
    [helper_vpermdq_ymm] = 1,
    [helper_vpgatherdd_ymm] = 1,
    [helper_vpgatherdq_ymm] = 1,
    [helper_vpgatherqd_ymm] = 1,
    [helper_vpgatherqq_ymm] = 1,
    [helper_vpmaskmovd_st_ymm] = 1,
    [helper_vpmaskmovq_st_ymm] = 1,
    [helper_comisd] = 1,
    [helper_ucomisd] = 1,
    [helper_cvtsq2sd] = 1,
    [helper_cvttsd2sq] = 1,
    [helper_mulsd] = 1,
};

const uint64_t xreg_offsets[XREG_MAX] = {
    [rax] = ENV_OFFSET_rax,
    [rcx] = ENV_OFFSET_rcx,
    [rdx] = ENV_OFFSET_rdx,
    [rbx] = ENV_OFFSET_rbx,
    [rsp] = ENV_OFFSET_rsp,
    [rbp] = ENV_OFFSET_rbp,
    [rsi] = ENV_OFFSET_rsi,
    [rdi] = ENV_OFFSET_rdi,
    [r8] = ENV_OFFSET_r8,
    [r9] = ENV_OFFSET_r9,
    [r10] = ENV_OFFSET_r10,
    [r11] = ENV_OFFSET_r11,
    [r12] = ENV_OFFSET_r12,
    [r13] = ENV_OFFSET_r13,
    [r14] = ENV_OFFSET_r14,
    [r15] = ENV_OFFSET_r15,
#if AOT_LEVEL == AOT_LEVEL_MAX
    [cc_src] = ENV_OFFSET_cc_src,
    [cc_dst] = ENV_OFFSET_cc_dst,
    [cc_op] = ENV_OFFSET_cc_op,
#endif
    [rip] = ENV_OFFSET_rip,
};

const CVectorType cvector_type_for_llvm_type[LLVMMAXType] = {
    [LLVMVector2xi64] = v2ulong,
    [LLVMVector4xi32] = v4uint,
    [LLVMVector8xi16] = v8ushort,
    [LLVMVector16xi8] = v16uchar,
    [LLVMVector4xi64] = v4ulong,
    [LLVMVector8xi32] = v8uint,
    [LLVMVector16xi16] = v16ushort,
    [LLVMVector32xi8] = v32uchar,
};

// FIXME: sanity check and cover more helpers
const int helper_do_not_sync_vector[HELPER_MAX] = {
    [helper_cpuid] = 1,
    [helper_rdtsc] = 1,
};
