#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <string.h>
#include "instr_def_ast.h"
#include "instr_def_parser.tab.h"
#include "instr_def_lexer.yy.h"
#include <stdbool.h>

extern char *lineptr;

static uint32_t fields_next_capacity = 512;
static uint32_t fields_capacity = 0;
static uint32_t fields_idx = 0;
static uint32_t *fields_is_imm = NULL;
static char **fields_type_list = NULL;
static char **fields_name_list = NULL;
static uint32_t *instr_def_field_offset = NULL;
static uint32_t *instr_def_field_cnt = NULL;
static char **instr_def = NULL;
static uint32_t instr_def_idx = 0;
static uint32_t last_fields_idx = 0;

static void get_more_space() {
    fields_is_imm = reallocarray(fields_is_imm, fields_next_capacity, sizeof(uint32_t));
    assert(fields_is_imm);
    fields_type_list = reallocarray(fields_type_list, fields_next_capacity, sizeof(char *));
    assert(fields_type_list);
    fields_name_list = reallocarray(fields_name_list, fields_next_capacity, sizeof(char *));
    assert(fields_name_list);
    instr_def_field_offset = reallocarray(instr_def_field_offset, fields_next_capacity, sizeof(uint32_t));
    assert(instr_def_field_offset);
    instr_def_field_cnt = reallocarray(instr_def_field_cnt, fields_next_capacity, sizeof(uint32_t));
    assert(instr_def_field_cnt);
    instr_def = reallocarray(instr_def, fields_next_capacity, sizeof(char *));
    assert(instr_def);
    fields_capacity = fields_next_capacity;
    fields_next_capacity *= 2;
}

void insert_field(const char *type, const char *name) {
    if ((fields_idx + 1) > fields_capacity) {
        get_more_space();
    }
    if (strstr(name, "slot") && strstr(name, "_idx")) {
        fields_is_imm[fields_idx] = 0;
        fields_idx += 1;
    } else if (strstr(name, "imm")) {
        fields_is_imm[fields_idx] = 1;
        fields_type_list[fields_idx] = type;
        fields_name_list[fields_idx] = name;
        fields_idx += 1;
    }
}

void handle_def(const char *instr) {
    assert((instr_def_idx + 1) < fields_capacity);
    instr_def[instr_def_idx] = instr;
    instr_def_field_offset[instr_def_idx] = last_fields_idx;
    instr_def_field_cnt[instr_def_idx] = (fields_idx - last_fields_idx);
    last_fields_idx = fields_idx;
    instr_def_idx += 1;
}

void gen_api() {
    printf("/* DO NOT EDIT: this is generated by instr_def_parser from instr_def.h */\n");
    printf("#include \"tcg_ast.h\"\n");
    printf("#include <assert.h>\n");
    printf("\n");
    /// get_operand
    printf("OperandType get_operand(void *ptr, uint32_t idx, uint32_t *is_imm) {\n");
    printf("    OperandType ret;\n");
    printf("    ret.s.valid = 0;\n");
    printf("    Instr1B2 *iptr = (Instr1B2 *)ptr;\n");
    printf("    if (iptr->instr_type == SIZE2B) {\n");
    printf("        return ret;\n");
    printf("    } else if (iptr->instr_type == SIZE4B) {\n");
    printf("        Instr4B *i_Instr4B = (Instr4B *)ptr;\n");
    printf("        if (idx == 0) {\n");
    printf("            ret.s.valid = 1;\n");
    printf("            ret.s.slot_type = i_Instr4B->slot0_type;\n");
    printf("            ret.s.slot_idx = i_Instr4B->slot0_idx;\n");
    printf("        } else if (idx == 1) {\n");
    printf("            ret.s.valid = 1;\n");
    printf("            ret.s.slot_type = i_Instr4B->slot1_type;\n");
    printf("            ret.s.slot_idx = i_Instr4B->slot1_idx;\n");
    printf("        }\n");
    printf("        return ret;\n");
    printf("    } else if (iptr->instr_type == SIZE6B) {\n");
    printf("        Instr2B4 *i_Instr2B4 = (Instr2B4 *)ptr;\n");
    printf("        if (idx == 0) {\n");
    printf("            ret.s.valid = 1;\n");
    printf("            ret.s.slot_type = i_Instr2B4->slot0_type;\n");
    printf("            ret.s.slot_idx = i_Instr2B4->slot0_idx;\n");
    printf("        }\n");
    printf("        return ret;\n");
    printf("    }\n");
    printf("    switch (iptr->instr_type_ext) {\n");

    for (uint32_t j = 0; j < instr_def_idx; ++j) {
    char *instr = instr_def[j];
    printf("    case %s_ext:\n", instr);
    printf("    %s *i_%s = (%s *)ptr;\n", instr, instr, instr);
    uint32_t s_idx = 0;
    for (uint32_t i = instr_def_field_offset[j]; i < (instr_def_field_offset[j] + instr_def_field_cnt[j]); ++i) {
        if (i == instr_def_field_offset[j]) {
            printf("    if (idx == %d) {\n", (i - instr_def_field_offset[j]));
        } else {
            printf("    } else if (idx == %d) {\n", (i - instr_def_field_offset[j]));
        }
        if (fields_is_imm[i]) {
            printf("        *is_imm = 1;\n");
            if (fields_type_list[i][0] == 'u') {
                printf("        ret.i = i_%s->%s;\n", instr, fields_name_list[i]);
            } else {
                printf("        ret.i = (uint64_t)((int64_t)i_%s->%s);\n", instr, fields_name_list[i]);
            }
        } else {
            printf("        ret.s.valid = 1;\n");
            printf("        ret.s.slot_type = i_%s->slot%d_type;\n", instr, s_idx);
            printf("        ret.s.slot_idx = i_%s->slot%d_idx;\n", instr, s_idx);
            s_idx += 1;
        }
    }
    if (instr_def_field_cnt[j] > 0) {
        printf("    }\n");
    }
    printf("    break;\n", instr);
    }

    printf("    default: assert(0);\n");
    printf("    }\n");
    printf("    return ret;\n");
    printf("}\n");
    /// move_to_next
    printf("\n");
    printf("void *move_to_next(void *ptr) {\n");
    printf("    Instr1B2 *iptr = (Instr1B2 *)ptr;\n");
    printf("    if (iptr->instr_type == SIZE2B) {\n");
    printf("        ptr += 2;\n");
    printf("        return ptr;\n");
    printf("    } else if (iptr->instr_type == SIZE4B) {\n");
    printf("        ptr += 4;\n");
    printf("        return ptr;\n");
    printf("    } else if (iptr->instr_type == SIZE6B) {\n");
    printf("        ptr += 6;\n");
    printf("        return ptr;\n");
    printf("    }\n");
    printf("    switch (iptr->instr_type_ext) {\n");

    for (uint32_t j = 0; j < instr_def_idx; ++j) {
    char *instr = instr_def[j];
    printf("    case %s_ext:\n", instr);
    printf("    ptr += sizeof(%s);\n", instr);
    printf("    break;\n", instr);
    }

    printf("    default: assert(0);\n");
    printf("    }\n");
    printf("    return ptr;\n");
    printf("}\n");
}

void parse_tcg_instructions(const char *filename) {
    FILE *source_file = fopen(filename, "r");
    if (!source_file) {
        perror("Error opening source file");
        return;
    }

    yyscan_t scanner;
    yylex_init(&scanner);
    yyset_in(source_file, scanner);

    yyparse(scanner);
    yylex_destroy(scanner);
    free(lineptr);
    fclose(source_file);
    return;
}

int main(int argc, const char *argv[]) {
  if (argc < 2) {
    printf("Usage: ./app <instr-def>\n");
    return -1;
  }
  parse_tcg_instructions(argv[1]);
  return 0;
}
