#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <string.h>
#include "instr_def_ast.h"
#include "instr_def_parser.tab.h"
#include "instr_def_lexer.yy.h"
#include <stdbool.h>

extern char *lineptr;

#define FIELDS_MAX  16
uint32_t fields_idx = 0;
uint32_t fields_is_imm[FIELDS_MAX] = {0};
char *fields_type_list[FIELDS_MAX] = {NULL};
char *fields_name_list[FIELDS_MAX] = {NULL};

void handle_def(const char *instr) {
    printf("    case %s_ext:\n", instr);
    printf("    %s *i_%s = (%s *)ptr;\n", instr, instr, instr);
    uint32_t s_idx = 0;
    for (uint32_t i = 0; i < fields_idx; ++i) {
        if (i == 0) {
            printf("    if (idx == %d) {\n", i);
        } else {
            printf("    } else if (idx == %d) {\n", i);
        }
        if (fields_is_imm[i]) {
            printf("        *is_imm = 1;\n");
            if (fields_type_list[i][0] == 'u') {
                printf("        ret.i = i_%s->%s;\n", instr, fields_name_list[i]);
            } else {
                printf("        ret.i = (uint64_t)((int64_t)i_%s->%s);\n", instr, fields_name_list[i]);
            }
        } else {
            printf("        ret.s.valid = 1;\n");
            printf("        ret.s.slot_type = i_%s->slot%d_type;\n", instr, s_idx);
            printf("        ret.s.slot_idx = i_%s->slot%d_idx;\n", instr, s_idx);
            s_idx += 1;
        }
    }
    if (fields_idx > 0) {
        printf("    }\n");
    }
    printf("    break;\n", instr);
    fields_idx = 0;
}

void insert_field(const char *type, const char *name) {
    if (strstr(name, "slot") && strstr(name, "_idx")) {
        fields_is_imm[fields_idx] = 0;
        fields_idx += 1;
    } else if (strstr(name, "imm")) {
        fields_is_imm[fields_idx] = 1;
        assert(fields_idx < FIELDS_MAX);
        fields_type_list[fields_idx] = type;
        fields_name_list[fields_idx] = name;
        fields_idx += 1;
    }
}

void parse_tcg_instructions(const char *filename) {
    FILE *source_file = fopen(filename, "r");
    if (!source_file) {
        perror("Error opening source file");
        return;
    }

    yyscan_t scanner;
    yylex_init(&scanner);
    yyset_in(source_file, scanner);

    yyparse(scanner);
    yylex_destroy(scanner);
    free(lineptr);
    fclose(source_file);
    return;
}

void gen_prolog() {
    printf("/* DO NOT EDIT: this is generated by instr_def_parser from instr_def.h */\n");
    printf("#include \"tcg_ast.h\"\n");
    printf("#include <assert.h>\n");
    printf("\n");
    printf("OperandType get_operand(void *ptr, uint32_t idx, uint32_t *is_imm) {\n");
    printf("    OperandType ret;\n");
    printf("    ret.s.valid = 0;\n");
    printf("    Instr1B2 *iptr = (Instr1B2 *)ptr;\n");
    printf("    assert(iptr->instr_type == SIZEXB);\n");
    printf("    switch (iptr->instr_type_ext) {\n");
}

void gen_epilog() {
    printf("    default: assert(0);\n");
    printf("    }\n");
    printf("    return ret;\n");
    printf("}\n");
}

int main(int argc, const char *argv[]) {
  if (argc < 2) {
    printf("Usage: ./app <instr-def>\n");
    return -1;
  }
  gen_prolog();
  parse_tcg_instructions(argv[1]);
  gen_epilog();
  return 0;
}
